/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class howdo1_NativeCallsClass */

#ifndef _Included_howdo1_NativeCallsClass
#define _Included_howdo1_NativeCallsClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     howdo1_NativeCallsClass
 * Method:    printOne
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_howdo1_NativeCallsClass_printOne
  (JNIEnv *, jclass);

/*
 * Class:     howdo1_NativeCallsClass
 * Method:    printTwo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_howdo1_NativeCallsClass_printTwo
  (JNIEnv *, jclass);

/*
 * Class:     howdo1_NativeCallsClass
 * Method:    createObject
 * Signature: (I)Lhowdo1/NativeCallsClass/MyObject;
 */
JNIEXPORT jobject JNICALL Java_howdo1_NativeCallsClass_createObject
  (JNIEnv *, jclass, jint);

/*
 * Class:     howdo1_NativeCallsClass
 * Method:    getObjectValue
 * Signature: (Lhowdo1/NativeCallsClass/MyObject;)I
 */
JNIEXPORT jint JNICALL Java_howdo1_NativeCallsClass_getObjectValue
  (JNIEnv *, jclass, jobject);

/*
 * Class:     howdo1_NativeCallsClass
 * Method:    setObjectValue
 * Signature: (Lhowdo1/NativeCallsClass/MyObject;I)V
 */
JNIEXPORT void JNICALL Java_howdo1_NativeCallsClass_setObjectValue
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
