/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ver1_Bridge */

#ifndef _Included_ver1_Bridge
#define _Included_ver1_Bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ver1_Bridge
 * Method:    createObject
 * Signature: (Ljava/lang/String;IZ)Lver1/User;
 */
JNIEXPORT jobject JNICALL Java_ver1_Bridge_createObject
  (JNIEnv *, jobject, jstring, jint, jboolean);

/*
 * Class:     ver1_Bridge
 * Method:    getObjectValue
 * Signature: (Lver1/User;)I
 */
JNIEXPORT jint JNICALL Java_ver1_Bridge_getObjectValue
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ver1_Bridge
 * Method:    setObjectValue
 * Signature: (Lver1/User;I)V
 */
JNIEXPORT void JNICALL Java_ver1_Bridge_setObjectValue
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     ver1_Bridge
 * Method:    testObj
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_ver1_Bridge_testObj
  (JNIEnv *, jobject);

/*
 * Class:     ver1_Bridge
 * Method:    test
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_ver1_Bridge_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
